FROM node:20-alpine AS prod

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i -g @nestjs/cli
RUN npm install --legacy-peer-deps

FROM prod AS build

COPY . .

RUN npm run build


FROM prod AS production

WORKDIR /app

COPY package*.json ./
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

EXPOSE 6666
CMD ["node", "dist/main"]

